version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn jobapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  db:
    image: sqlite:latest  # Note: In production, use PostgreSQL. This is a placeholder.
    volumes:
      - db_data:/var/lib/sqlite

  celery:
    build: ./backend
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  db_data:
